# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1278fa1e4d80ce62c7d5795aee4249054d889eb70efdf6d2b4d292f53a747ff36a4533ef1dec943d57698d667da4b3f1302957ebb36b83fe3c73b861a6d463b8

test:
  secret_key_base: 867b5f89c6375c00e9e4d16d41c604f3ed3d82c551ce27c0597894cd3c196d84045f9c1a7cadf40f352d7745e88fae7a65ef4663e86607c21c31cb9bbf27d816

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
